

import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./providers/ConvexClerkProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Podcast App By NEXT JS",
  description: "Generated by Sadman Showmik",
  icons:{
    icon: "/icons/logo.svg"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ConvexClientProvider>{children}</ConvexClientProvider>
        </body>
    </html>
  );
}
